### PR TITLE
corporate logos updated

### PR DESCRIPTION
**Pull request by ericanylee**
My B i closed the previous PR!!
still waiting on 3 logos 
screen shot 2016-08-29 at 11 27 13 pm

### CODE REVIEW

**Comment by ericanylee** [comment]
screen shot 2016-08-29 at 11 27 13 pm

**Comment by corlyleung** [comment]
If it's possible, can you rename this PR to something more relevant to the change?

**Comment by corlyleung** [comment]
Also, can you delete the old logo's that are no longer relevant? (Groupon.....)

**Comment by sskhandek** [comment]
Also, sorry to be nitpicky, but if we have all of those logos gone from the html, can we also remove them from the media?

**Comment by ericanylee** [comment]
@corlyleung I held on to Groupon just because I'm talking to them tomorrow about sponsorship options

@sskhandek from the media?

**Comment by sskhandek** [comment]
@ericanylee I mean that a lot of lines of html were deleted, can we also delete the accompanying files with them? Like all the ones located at IllinoisWCS.github.io/assets/img/logos/

**Comment by ericanylee** [comment]
@sskhandek I thought I did... but it's not showing will look into it

**Comment by sskhandek** [comment]
@ericanylee Do you need help? I can just submit your changes from my end if you're having some trouble.

**Comment by ericanylee** [comment]
@sskhandek yeah i reverted a commit and screwed something up..logo imgs aren't there in my branch...?😓

**Pull request merged**
