### PR TITLE
logos updated

### PR DESCRIPTION
**Pull request by ericanylee**
screen shot 2016-08-29 at 10 58 27 pm

Could someone make it look nicer since I dont know web programming at all pls. And still waiting on logos from 3 more companies

### CODE REVIEW

**Comment by corlyleung** [comment]
Did you edit index.html?

**Comment by ericanylee** [comment]
@corlyleung yep, included the screenshot

**Comment by corlyleung** [comment]
oo hmm, it's not showing up on files changed. Will check.

**Comment by ericanylee** [comment]
@corlyleung I thinkkk it's showing up on mine ?
screen shot 2016-08-29 at 11 14 49 pm

**Comment by sskhandek** [comment]
Nope, your branch doesn't have the change you're talking about. Can you try updating the branch with the index.html?

screen shot 2016-08-29 at 11 21 51 pm

**Comment by ericanylee** [comment]
wrong one

**Pull request closed without merging**
